Awesome books
Newtayo/Awesome-books pull request #1
Opened 2023-02-13 20:29 UTC by Newtayo

## Awesome Books

- [ ] Books are  added dynamically
- [ ] Local storage stores collection of books
- [ ] Remove and add buttons work perfectly

2023-02-13 21:11 UTC, anagudelogu requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi Team! @Newtayo @yodit93, 
I'm Andres.


While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Descriptive PR title, summary and commit messages. 💬 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-13 21:11 UTC, anagudelogu commented on script.js
> +/* eslint-disable no-use-before-define */
- [ ] You did a great job working on this milestone! 💯 However, please avoid disabling linter rules. Linters are used to ensure a consistent code format and some best practices. Please consider removing this disable and fixing the rule!

💡My suggestion:

You're getting this error because you are doing multiple things with the same function, e.g. this `bookremoval()` function is adding a click event listener to all `'.remove'` elements, is handling the logic for deleting a book (filter) and is handling the display and updating the store. Ending up with a circular dependency, (bookremoval uses display and display uses bookremoval) so there's no way you can reorganize your functions (in terms of ordering) to make the linter rule pass. Wouldn't it be better to keep your logic simple by giving each function a single responsibility?

In this case, you could do something like this:

```js
// displaying books logic
const display = () => {
  container.innerHTML = '';
  bookcollection.forEach((book) => {
    bookArrangement(book);
  });
}


// Removing book logic
const bookRemoval = (id) => {
  // returns a new array that doesn't contain the element with the given id
  return bookCollection.filter((book) => book.id !== id) 
}


// Listeners
const removeButtons = document.querySelectorAll('.remove')

removeButtons.forEach((btn) => {
  btn.addEventListener('click', () => {
    bookcollection = bookRemoval(btn.id)
    display()
    updatingStorage()
  }
}
```

Now, your `display` is only in charge of displaying the HTML for each book and your `bookRemoval` function is only responsible for the logic to remove a book. Now, you can use them inside your event listener without getting this linter error. Later in the program, you're going to learn about the Single responsibility principle. 🤓 🔧

2023-02-14 12:25 UTC, Newtayo commented on script.js
> +/* eslint-disable no-use-before-define */
Hello @anagudelogu. I tried implementing what you suggested by it is not working. Can you please assist

2023-02-14 14:04 UTC, DuaneDave approved these changes
Hi @Newtayo and @anagudelogu 👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Your awesome team play has made a great app
✔️ All linter checks are passing
✔️ All functionalities are implemented as expected 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-14 14:43 UTC, merged