Awesome books with class
Newtayo/Awesome-books pull request #3
Opened 2023-02-15 19:22 UTC by Newtayo

## Milestone

- [ ] Converted awesome books page to single page application.
- [ ] Nav Links have been added to the single page application to aid easy navigation of the pages.
- [ ] Passed all linter checks

2023-02-15 21:25 UTC, Ghiftee requested changes
## STATUS: CHANGES REQUIRED ♻️♻️
Hello @Newtayo and @yodit93 👋🏽 

Good job working on the project so far! 
To highlight 👍🏽 
✔️ App runs smoothly
✔️ Design matches wireframe
✔️ No linter errors

However, there are some issues that you need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
- I suggest you add the name of the second contributor to the project to your README. This would ensure both parties get credit for their work. 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-02-15 21:25 UTC, Ghiftee commented on script.js
>  /* eslint-disable max-classes-per-file */
- [ ] Let's try to not disable linters as they help us write better and cleaner code

2023-02-16 12:44 UTC, Newtayo commented
- [ ] Refactored the code to the use of just a class.
- [ ] Passed all linter checks
- [ ] Eslink disabled command removed from the code

2023-02-16 13:06 UTC, AmaduKamara approved these changes
# Status: Approved 🟢 🟢 🟢

Hi @Newtayo,

Good job working on the changes asked by the previous reviewer 👍🏽

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

## Highlights:

✅ You used Gitflow correctly 👍🏽
✅ Linter checks passed 👍🏽
✅ All sections in the navigation bar work fine as expected 👍🏽 
✅ Adding and removing a book works fine 👍🏽 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-02-16 13:06 UTC, AmaduKamara commented on index.html
> +      <input type="text" class="new-author" placeholder="Author">
[ Optional Changes ]

- [ ] What if you could clear the input fields when a book is added so the user doesn't have to manually clear them in order to add a new book?

2023-02-16 13:09 UTC, merged